gui:
  splitDiff: always
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --syntax-theme base16-256 -s
customCommands:
  - key: 'b'
    prompts:
      - type: 'input'
        title: 'What is the branch name?'
        initialValue: ''
    command: "git checkout -b mortadha.teffaha/{{index .PromptResponses 1}}"
    context: 'localBranches'
    loadingText: 'creating branch'
